### ISSUE TITLE
Implement: Communication Protocol

### ISSUE THREAD

**Issue by haiodo** [hardcoreeng/platform#11]
# Platform Protocol

This package provide implementation of platform communication protocol. 
It allow to create a client and server implementations, clients could connect to existing servers and servers could provide endpoints for client connections.

**Comment by z2sx** [comment]
1. Why do anyone need `clientId`?
2. As these API user, shall I ever use `createServer`? (Or this is just internal API?)
3. How `ClientConnection` relates to `Storage`? (where is `findAll`, etc?)
4. Why `storageFactory`?

Please provide full example how this API will be used to set up client and establish server connection.

**Comment by z2sx** [comment]
5. Why `target` from `createClient` but `host` and `port` for `createServer`? Why not use same parameters for both functions?

**Comment by haiodo** [comment]
Update docs.

**Comment by z2sx** [comment]
I think we should start doing it, and discuss real code in PR, because I'm not fully understand purpose of proposed interfaces without how they will be used in real life. Can we start with some simple real implementation?
