### ISSUE TITLE
Notification proposal

### ISSUE THREAD

**Issue by BykhovDenis** [hardcoreeng/platform#261]
The notification system should implement notifications of the user about new events on the UI.
These notifications allow to display how many objects have changed in the space, and / or the fact that the object has changed without details about the changes themselves.
More detailed information about object changes and notifications for example by e-mail or in a separate detailed UI should be created based on the implementation of Activity
(For UI, we can use the proposed scheme, but request transactions, and build an Activity based on them. For e-mail, I think, for not flood we can send with a delay (for example, 5 minutes, or customizable) and collect all changes for a given period
1. Notification for space's object. Simple sampling based on time of change is used.
The state is stored for each user and space to which user is subscribed.
When subscribing to a space, an object is created, when unsubscribing, it is deleted.
The watch time is updated when called `txHandle` and` findall` in query.

```
interface LastViewed extends Doc {
  objectClass: Ref <Class <Doc>>
  objectSpace: Ref <Space>
  client: Ref <Account>
  lastTime: Timestamp
} 
```

To view new objects, we get the time of the last view of the space and use it in the request
To do this, it will be necessary to implement the `$ gt` selector

2. Notifications for changes in the object are built on the same principle.
If there is a subscription to a space and objects of the space containing it, priority is given to the subscription to the space

```
interface ObjectLastViewed extends LastViewed {
  objectIDs: Ref <Doc>[]
} 
```

**Comment by BykhovDenis** [comment]
And additional we can create external notifications like a mention
```
Interface Notification extends Doc {
  objectClass: Ref<Class<Doc>>
  objectSpace: Ref<Space>
  objectId: Ref<Doc>
  client: Ref<Account>
}
```

As example for chunter:
check channel subscribe by findall `LastViewed` with current spaceId
if founded get all messages where modifiedBy greater then `lastTime` and after we can use it for somehow mark this messages as unread
if `LastViewed` not founded get `Notification` for this space, and union its with `objectLastViewed`

For see notification's object we need do funtion in ListView (or something else) to autoscroll to fixed place

**Comment by BykhovDenis** [comment]
На примере chunter предлагаю выделять новые сообщения другим фоном и возможно полосой сбоку. Количество новых сообщений в канале отображать на обычном фоне при отсутствии mention и акцентированным при их наличии(можно ограничить счетчик до 99+). Количество Replies треда можно отображать только для новых ответов (при этом аватары отвечающих отображаются всегда при их наличии). Сообщение считается прочитанным при условии нахождения его в поле видимости в течении 3-10 секунд и активном статусе пользователя. При отсутствии активности пользователя в течении 30-60 секунд статус пользователя меняется на отошел и автоскролл отключается. По клику на количество новых сообщений(в спейсе или replies) если нет mention происходит отметка о прочтении всех, при наличии mention переход к первому непрочитанному mention
![изображение](https://user-images.githubusercontent.com/80476319/130203565-98f6d105-a6bd-459c-a7ce-ad15685c162e.png)

**Comment by BykhovDenis** [comment]
![изображение](https://user-images.githubusercontent.com/80476319/130470036-f0f66035-3791-4dbc-83cb-173bf0f4baa6.png)
Для task необходима подписка на объекты, автоматически подписывать пользователя при назначении задачи на него, и отписывать при изменении назначения. Позволить пользователю подписываться и отписываться нажатием на соответствующую иконку. При наличии комментария с mention подсвечивать кол-во комментариев акцентированным цветом, подсвечивать фон у отслеживаемых измененных задач. В окне редактирования подсвечивать измененные поля, считать их прочитанными при фокусе на соответствующее поле.

**Comment by BykhovDenis** [comment]
Уведомления должны иметь различный приоритет. (Например mention должен быть более приоритетным чем новое сообщение, новое сообщение в direct более приоритетным чем сообщение без mention в канале). Необходимо заложить возможность настройки уведомлений и отправки их через различные сервисы с предварительной группировкой. Для создания приоритетных уведомлений хорошо подойдет DerivedData, но использование для чата такое решение кажется избытычным

**Comment by BykhovDenis** [comment]
https://docs.google.com/document/d/16_k0qhYzeTeeRj1jOreNATCbw4wLgmiE1-i_S9jXOHE/edit?usp=sharing

**Comment by haiodo** [comment]
It is implemented and working, but need to be reviewed to apply it is working fine.
