### ISSUE TITLE
Cannot open dev server locally

### ISSUE THREAD

**Issue by keepitsimple** [hardcoreeng/platform#306]
I successfully installed locally the project in accordance with documentation in `Readme.md`

I also did `rush build ` after `rush updated`. All looks good

```bash
roman@devserver:dev/server ‹main›$ rushx dev
Found configuration in /home/roman/work/aplatov/platform/rush.json


Rush Multi-Project Build Tool 5.50.0 - https://rushjs.io
Node.js version is 14.17.5 (LTS)

Found configuration in /home/roman/work/aplatov/platform/rush.json

Executing: "ts-node ./src/index.ts"

Starting Server + Auth Server
starting server on port 18080...
server is listening on host: 127.0.0.1: 18080 
auth server is started at  { address: '::', family: 'IPv6', port: 3000 }
Serve and Auth server are up and running

```

I also started `mongo` & `elasticsearch` docker containers

 but when I request http://localhost:18080 it hang.

**Comment by z2sx** [comment]
I believe you need to go to http://localhost:8080/component:login.LoginApp 
Created issue for this: #308 

Alternatively, you may play with `dev` version (in-memory database). Just run `rushx dev` from `dev/prod` and go to http://localhost:8080/component:workbench.WorkbenchApp

**Comment by keepitsimple** [comment]
Thank you! Workbench works for me locally
