### ISSUE TITLE
Do not store transactions with notification updates

### ISSUE THREAD

**Issue by haiodo** [hardcoreeng/platform#309]
We need to have a way to minimize amount of transactions for some kind of model data. 
For example we could put into a Channel a notification collection per individual user, and have a lot of transactions of this kind. But we do not need to have a dozen of such transactions.

After checking some ideas, I think we could combine transactions( for part of data), so we could mark some of attributes to be extracted into special snapshot transaction.

So if we have such attribute found in update/create transaction we perform split of Tx to two:
* one original(without marked attributes)  - if there is no more attributes, and it is updateTx it should be omitted.
* and one with marked attributes but special Id '{objectId}-volatile' identifier and all marked values. 
Storage should combine this kind of transactions then update is performed.
 
So it will be just 1 snapshot Tx available only if this fields are changed. So we will have such fields so be stored in one Tx.

**Comment by haiodo** [comment]
After checking some ideas, I think we do not need to combine transactions, a better way is to mark some of attributes to be not stored in transactions, but be available only as derived data snapshot.

And we only need on server to not store update transactions with empty operations inside. So if we filter non storable values, from Tx, and add this check we automatically have non storing of Txes for derived data/or notifications.

**Comment by BykhovDenis** [comment]
Maybe we can use new tx class for simplify?

**Comment by haiodo** [comment]
This is not required anymore.
