### ISSUE TITLE
Incorrect table in popups

### ISSUE THREAD

**Issue by BykhovDenis** [hardcoreeng/platform#538]
![изображение](https://user-images.githubusercontent.com/80476319/140469117-ee5c77ff-80a0-4bdf-80e6-2cd914673e2f.png)
![изображение](https://user-images.githubusercontent.com/80476319/140469513-e508e09a-c413-4c93-bbc6-bbd82cdecd6c.png)
![изображение](https://user-images.githubusercontent.com/80476319/140469554-49cb97ce-1735-4d0b-b232-6bd665f330b6.png)

**Comment by sumboid** [comment]
@BykhovDenis Most likely in general case you'll need table with dynamic height which is AFAIK not possible in virtualized case. So feel free to add `export let virtual: boolean` and render table without virtualization with sticky header.
