### ISSUE TITLE
Remove use of `walk` method

### ISSUE THREAD

**Issue by benmccann** [hardcoreeng/platform#584]
This is going away in Svelte 5:
https://github.com/hardcoreeng/platform/blob/8e74e94a53b4a96262e980ebcec6b752f1018fde/dev/ui-build/src/componentParser.ts#L7

Replace with `import { walk } from 'estree-walker';`

**Comment by haiodo** [comment]
Thanks @benmccann, this codebase actually are outdated and this functionality is not used.

**Comment by haiodo** [comment]
Actual repository for next version of platform are here: http://github.com/hcengineering/anticrm

**Comment by benmccann** [comment]
Sounds good. Maybe this repo should be archived?
