### ISSUE TITLE
Refactor `Doc` and `VDoc` transactions

### ISSUE THREAD

**Issue by z2sx** [hardcoreeng/platform#75]
`user` and `timestamp` makes sense for `Tx` (not `VDoc`) transactions as well, so it looks like we can avoid `VDoc` transactions at all. Remaining question is `space` with is required for `VDoc` and makes no sense for `model` domain, but I think if we provide `undefined` space for model transactions everything will be fine. Who knows, later we may employ spaces for `model` domain as well.

So I propose to add following properties to `Tx` class:

* `space?: Ref<Space>`
* `user: Ref<Account>`
* `timestamp: number`

Very likely `user` and `timestamp` will be set on server side, but for now let's set them on client.

Thoughts?

**Comment by haiodo** [comment]
Sounds good, please take a look: https://github.com/hardcoreeng/platform/pull/76
